<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>gitadr</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Git.Core\Git.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="..\Libs\diff_tool.dll">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>
